#include "DirectXShaderCompiler/lib/DxcSupport/dxcapi.use.cpp"
#include "DirectXShaderCompiler/lib/DxcSupport/dxcmem.cpp"
#include "DirectXShaderCompiler/lib/DxcSupport/FileIOHelper.cpp"
#include "DirectXShaderCompiler/lib/DxcSupport/Global.cpp"
#include "DirectXShaderCompiler/lib/DxcSupport/HLSLOptions.cpp"
#include "DirectXShaderCompiler/lib/DxcSupport/Unicode.cpp"
#include "DirectXShaderCompiler/lib/DxcSupport/WinAdapter.cpp"
#include "DirectXShaderCompiler/lib/DxcSupport/WinFunctions.cpp"
