#include "DirectXShaderCompiler/lib/Transforms/Scalar/ADCE.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/AlignmentFromAssumptions.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/BDCE.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/ConstantHoisting.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/ConstantProp.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/CorrelatedValuePropagation.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/DCE.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/DeadStoreElimination.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/EarlyCSE.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/FlattenCFGPass.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/Float2Int.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/GVN.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/HoistConstantArray.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/IndVarSimplify.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/JumpThreading.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LICM.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoadCombine.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopDeletion.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopDistribute.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopIdiomRecognize.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopInstSimplify.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopInterchange.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopRerollPass.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopRotation.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopStrengthReduce.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopUnrollPass.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LoopUnswitch.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LowerAtomic.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LowerExpectIntrinsic.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/LowerTypePasses.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/MemCpyOptimizer.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/MergedLoadStoreMotion.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/NaryReassociate.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/PartiallyInlineLibCalls.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/PlaceSafepoints.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/Reassociate.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/Reg2Mem.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/Reg2MemHLSL.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/RewriteStatepointsForGC.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/SCCP.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/SROA.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/SampleProfile.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/Scalar.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/ScalarReplAggregates.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp"#include "DirectXShaderCompiler/lib/Transforms/Scalar/# HLSL Change
#include "DirectXShaderCompiler/lib/Transforms/Scalar/DxilLoopUnroll.cpp" # HLSL Change
#include "DirectXShaderCompiler/lib/Transforms/Scalar/DxilRemoveDeadBlocks.cpp" # HLSL Change
#include "DirectXShaderCompiler/lib/Transforms/Scalar/DxilEraseDeadRegion.cpp" # HLSL Change
#include "DirectXShaderCompiler/lib/Transforms/Scalar/DxilFixConstArrayInitializer.cpp" # HLSL Change
#include "DirectXShaderCompiler/lib/Transforms/Scalar/DxilEliminateVector.cpp" # HLSL Change
#include "DirectXShaderCompiler/lib/Transforms/Scalar/DxilConditionalMem2Reg.cpp" # HLSL Change
#include "DirectXShaderCompiler/lib/Transforms/Scalar/DxilRemoveUnstructuredLoopExits.cpp" # HLSL Change
#include "DirectXShaderCompiler/lib/Transforms/Scalar/Scalarizer.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/SeparateConstOffsetFromGEP.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/SimplifyCFGPass.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/Sink.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/SpeculativeExecution.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/StraightLineStrengthReduce.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/StructurizeCFG.cpp"
#include "DirectXShaderCompiler/lib/Transforms/Scalar/TailRecursionElimination.cpp"
